### ISSUE TITLE
How to run migrations on this after installing via PIP?

### ISSUE THREAD

**Issue by Bulletninja** [andytwoods/zappa-call-later#1]
I installed zappa-call-later via pip, and i see there is a migration file in the project but it doesn't run if i do a `migrate.py migrate`. I tried setting it up in installed_apps as `zappa_call_later` but it says

> No module named 'zappa_call_later'

**Comment by andytwoods** [comment]
Will have a look when the kids are napping later. It might be that that migration file needs removing and we createmigrations before running migrate.

**Comment by andytwoods** [comment]
There was a pypi issue that I fixed. Should all work as expected now.
