### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by klowe0100** [andytwoods/zappa-call-later#2]
Hi @andytwoods ,  thanks for sharing your work. Is this approach still viable today or maybe you've found a better solution? I'm trying to schedule the execution of tasks specific time into the future. I tried using https://pypi.org/project/django4-background-tasks/ which seems like a similar approach to yours but the asks aren't being found in lambda when I run the management command. Thanks for any insights! Happy to put in some time to help update this package if it's the best path forward.

**Comment by andytwoods** [comment]
Wise to go with a different approach. Consider too Zappa has been discontinued.
